### PR TITLE
Centos 7, Ubuntu 14, Ubuntu 16

### PR DESCRIPTION
**Pull request by netflash**
Update version of OpenVPN AS

### CODE REVIEW

**Comment by netflash** [comment]
Looks like there's a lot of outdated stuff. Gonna update it soon to fix CI builds.

**Comment by rjocoleman** [comment]
hey @netflash thanks for this!

I don't currently use Chef or OpenVPN.. how would you feel about commit access as I can't reasonably test this.. it looks like you're all over it!

**Comment by netflash** [comment]
Hey @rjocoleman,

I can take it over here and in the supermarket, or you can just add me as a contributor. 
Your call.

Also I think about removing chefspec in favour of test kitchen, cause this cookbook can't really be tested by chef spec.

**Comment by rjocoleman** [comment]
thanks @netflash I've set you up in Supermarket as the owner. I'll transfer here too, you've just got a fork with the same name so I can't yet!

**Comment by rjocoleman** [comment]
I'm glad this is helpful btw 👍

**Comment by netflash** [comment]
@rjocoleman I renamed the fork. You can go ahead.
Thanks!

**Comment by rjocoleman** [comment]
ah sorry now it's erroring with `netflash already has a repository in the rjocoleman/openvpnas network`

**Comment by rjocoleman** [comment]
maybe push your branch here, kill this PR and your fork then I'll transfer?

**Comment by netflash** [comment]
Good idea. In this case I need R/W access first, right ?

**Comment by rjocoleman** [comment]
yep - there should be a Collaborator invite in your inbox?

**Comment by netflash** [comment]
Yup, I did the push. Creating PR in a few.

**Comment by netflash** [comment]
Thanks, @rjocoleman. I will take care of this cookbook until someone wants to take it over from me :-)

**Pull request closed without merging**
